query User($pk: Int!) {
  User(pk: $pk) {
    ... on QueryUserSuccess {
      data {
        pk
        id
        name
      }
    }
    ... on ZodError {
      message
    }
    ... on Error {
      message
    }
  }
}
